spring.application.name=simpsonsmcp
spring.main.web-application-type=none
spring.ai.mcp.server-name=simpsons-mcp
spring.ai.mcp.server-version=0.0.1

#needed to make it work
spring.main.banner-mode=off
logging.pattern.console=